export const enum Slot {
  TOP = "TOP",
  SOCK = "SOCK",
  SHOE = "SHOE",
  OUTERWEAR = "OUTERWEAR",
  HAIR = "HAIR",
  FACE = "FACE",
  DRESS = "DRESS",
  BOTTOM = "BOTTOM",
  BACKGROUND = "BACKGROUND",
  ACCESSORY = "ACCESSORY",
}
